spring:
  application:
    name: service-auth
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/newbee_mall_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
  main:
    allow-bean-definition-overriding: true


server:
  port: 8090


#logging.level.org.springframework.security: DEBUG
mybatis:
  mapper-locations: /mapper/*Mapper.xml

