spring:
  application:
    name: service-auth

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 123456


server:
  port: 9098


#logging.level.org.springframework.security: DEBUG
mybatis:
  mapper-locations: /mapper/*Mapper.xml

